### PR TITLE
Tooling

### PR DESCRIPTION
**Pull request by RyanHirsch**
This is a work in progress, it has lots of errors because I don't want to make presumptions around what styling you think is important. It should address #1 that I created.

Here is an example of what is currently flagged with these rules:
Screenshot 2023-03-13 at 3 59 35 PM

### CODE REVIEW

**Comment by RyanHirsch** [comment]
Here's the whole log output

```txt

> transcriptator@1.0.0 lint:eslint
> eslint src/ test/


transcriptator/src/formats/html.ts
   2:1   error  There should be at least one empty line between import groups                        import/order
   3:1   error  `node-html-parser` import should occur before import of `../timestamp`               import/order
   8:9   error  'outSegments' is never reassigned. Use 'const' instead                               prefer-const
  20:39  error  Refactor this function to reduce its Cognitive Complexity from 20 to the 15 allowed  sonarjs/cognitive-complexity
  63:21  error  Expected property shorthand                                                          object-shorthand

transcriptator/src/formats/json.ts
   19:30  error    Don't use `Object` as a type. The `Object` type actually means "any non-nullish value", so it is marginally better than `unknown`.
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead  @typescript-eslint/ban-types
   41:13  error    Expected property shorthand                                                                                                                                                                                                                                                                      object-shorthand
   71:36  warning  Unexpected any. Specify a different type                                                                                                                                                                                                                                                         @typescript-eslint/no-explicit-any
  101:17  error    Don't use `Object` as a type. The `Object` type actually means "any non-nullish value", so it is marginally better than `unknown`.
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead  @typescript-eslint/ban-types
  101:32  warning  Unexpected any. Specify a different type                                                                                                                                                                                                                                                         @typescript-eslint/no-explicit-any

transcriptator/src/formats/srt.ts
   17:24  warning  'parseSRTSegment' was used before it was defined  @typescript-eslint/no-use-before-define
   18:5   error    Assignment to function parameter 'lastSpeaker'    no-param-reassign
   25:14  error    Expected property shorthand                       object-shorthand
   25:32  error    Expected property shorthand                       object-shorthand
   29:9   warning  'parseSRTSegment' was used before it was defined  @typescript-eslint/no-use-before-define
   41:37  error    Expected '!==' and instead saw '!='               eqeqeq
   43:25  error    's' is never reassigned. Use 'const' instead      prefer-const
   59:29  error    Expected '!==' and instead saw '!='               eqeqeq
   61:17  error    's' is never reassigned. Use 'const' instead      prefer-const
   74:26  error    Expected '===' and instead saw '=='               eqeqeq
   81:14  warning  Unexpected constant condition                     no-constant-condition
   87:19  error    Missing radix parameter                           radix
   97:31  error    Expected '!==' and instead saw '!='               eqeqeq
  112:9   error    Expected property shorthand                       object-shorthand
  113:9   error    Expected property shorthand                       object-shorthand
  114:9   error    Expected property shorthand                       object-shorthand
  116:9   error    Expected property shorthand                       object-shorthand

transcriptator/src/formats/vtt.ts
   1:1   error  There should be at least one empty line between import groups  import/order
   8:13  error  Expected '!==' and instead saw '!='                            eqeqeq
  14:5   error  Assignment to function parameter 'data'                        no-param-reassign

transcriptator/src/index.ts
   20:5   error  Assignment to function parameter 'data'                                       no-param-reassign
   25:16  error  Unnecessary 'else' after 'return'                                             no-else-return
   54:9   error  Assignment to function parameter 'transcriptFormat'                           no-param-reassign
   57:5   error  Assignment to function parameter 'data'                                       no-param-reassign
   94:9   error  Assignment to function parameter 'body'                                       no-param-reassign
   96:9   error  Assignment to function parameter 'body'                                       no-param-reassign
  113:9   error  'newSegment' is never reassigned. Use 'const' instead                         prefer-const
  131:69  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types
  134:32  error  Expected '!==' and instead saw '!='                                           eqeqeq
  138:9   error  'outSegments' is never reassigned. Use 'const' instead                        prefer-const
  143:32  error  'count' is defined but never used. Allowed unused args must match /^_/u       @typescript-eslint/no-unused-vars

transcriptator/src/timestamp.ts
   6:12  error  Unnecessary 'else' after 'return'                                                                                 no-else-return
  15:11  error  Use object destructuring                                                                                          prefer-destructuring
  21:28  error  Expected '===' and instead saw '=='                                                                               eqeqeq
  22:21  error  Missing radix parameter                                                                                           radix
  22:53  error  Missing radix parameter                                                                                           radix
  22:80  error  Missing radix parameter                                                                                           radix
  23:28  error  Expected '===' and instead saw '=='                                                                               eqeqeq
  24:21  error  Missing radix parameter                                                                                           radix
  24:48  error  Missing radix parameter                                                                                           radix
  25:28  error  Expected '===' and instead saw '=='                                                                               eqeqeq
  26:21  error  Missing radix parameter                                                                                           radix
  29:14  error  Missing radix parameter                                                                                           radix
  30:9   error  Unexpected use of 'isNaN'. Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan  no-restricted-globals
  32:19  error  Expected '!==' and instead saw '!='                                                                               eqeqeq
  33:9   error  Assignment (=) can be replaced with operator assignment (/=)                                                      operator-assignment
  37:9   error  Unexpected use of 'isNaN'. Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan  no-restricted-globals

transcriptator/test/custom.d.ts
  2:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

transcriptator/test/html.test.ts
    1:1   error  There should be at least one empty line between import groups                                                     import/order
    3:1   error  There should be at least one empty line between import groups                                                     import/order
    6:7   error  Variable name `_HTML_SEGMENTS_BOTH` must match one of the following formats: camelCase, PascalCase, UPPER_CASE    @typescript-eslint/naming-convention
   21:7   error  Variable name `_HTML_SEGMENTS_2_ONLY` must match one of the following formats: camelCase, PascalCase, UPPER_CASE  @typescript-eslint/naming-convention
   61:48  error  'id' is defined but never used. Allowed unused args must match /^_/u                                              @typescript-eslint/no-unused-vars
  159:50  error  'id' is defined but never used. Allowed unused args must match /^_/u                                              @typescript-eslint/no-unused-vars
  168:88  error  'id' is defined but never used. Allowed unused args must match /^_/u                                              @typescript-eslint/no-unused-vars

transcriptator/test/json.test.ts
   1:1   error  There should be at least one empty line between import groups         import/order
   3:1   error  There should be at least one empty line between import groups         import/order
  47:48  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  69:47  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

transcriptator/test/speaker.test.ts
  1:1  error  There should be at least one empty line between import groups  import/order

transcriptator/test/srt.test.ts
    1:1   error  There should be at least one empty line between import groups         import/order
    3:1   error  There should be at least one empty line between import groups         import/order
   95:48  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  116:48  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

transcriptator/test/temp.js
  7:7   error  'convertFile' is assigned a value but never used     @typescript-eslint/no-unused-vars
  7:28  error  'transcriptType' is assigned a value but never used  @typescript-eslint/no-unused-vars

transcriptator/test/test.ts
    1:1   error  There should be at least one empty line between import groups         import/order
    3:1   error  There should be at least one empty line between import groups         import/order
   66:79  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  126:79  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  174:28  error  Unexpected string concatenation of literals                           no-useless-concat
  174:35  error  Unexpected string concatenation of literals                           no-useless-concat
  174:43  error  Unexpected string concatenation of literals                           no-useless-concat
  174:79  error  Unexpected string concatenation of literals                           no-useless-concat
  178:63  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  211:13  error  Assignment to function parameter 'segments'                           no-param-reassign
  214:13  error  Assignment to function parameter 'expected'                           no-param-reassign
  253:66  error  'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

transcriptator/test/test_utils.ts
   2:1   error  There should be at least one empty line between import groups  import/order
  41:13  error  Expected property shorthand                                    object-shorthand

transcriptator/test/timestamp.test.ts
   1:1   error    There should be at least one empty line between import groups         import/order
  75:46  error    'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  82:15  warning  Unexpected any. Specify a different type                              @typescript-eslint/no-explicit-any
  90:46  error    'id' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

transcriptator/test/vtt.test.ts
  1:1  error  There should be at least one empty line between import groups  import/order
  2:1  error  There should be at least one empty line between import groups  import/order

✖ 96 problems (89 errors, 7 warnings)
  35 errors and 0 warnings potentially fixable with the `--fix` option.

```

**Comment by stevencrader** [comment]
I have no experience with eslint or desire for a specific style. I am happy to use your suggestions.

**Comment by RyanHirsch** [comment]
@stevencrader I've made the updates, let me know what you think.

**Comment by stevencrader** [comment]
Thank you for your support. I appreciate the help with getting eslint setup. It was in my mental checklist.

I'll push a change soon that removes the standalone prettier action

**Pull request merged**
